baseURL: https://www.hamot.pl/
theme: hugobricks
defaultContentLanguage: pl
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  pl:
    languageName: Polski
    contentDir: content/pl
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /uslugi/:slug
        products: /sklep/:slug
      section:
        posts: /blog/
        services: /uslugi/
        products: /sklep/
  en:
    languageName: English
    contentDir: content/en
    weight: 2
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
        products: /shop/:slug
      section:
        posts: /blog/
        services: /services/
        products: /shop/
